"""add candidate knowledge base schema

Revision ID: 8e2f969404b8
Revises: 5119a2b514c9
Create Date: 2026-09-18 18:45:32.034136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e2f969404b8'
down_revision: Union[str, Sequence[str], None] = '5119a2b514c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('candidate_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('activity_type', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_activities_candidate_id'), 'candidate_activities', ['candidate_id'], unique=False)
    op.create_table('candidate_application_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('fact_key', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'fact_key', name='uq_candidate_application_fact')
    )
    op.create_index(op.f('ix_candidate_application_facts_candidate_id'), 'candidate_application_facts', ['candidate_id'], unique=False)
    op.create_table('candidate_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('awarded_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_awards_candidate_id'), 'candidate_awards', ['candidate_id'], unique=False)
    op.create_table('candidate_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('credential_id', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('credential_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_certifications_candidate_id'), 'candidate_certifications', ['candidate_id'], unique=False)
    op.create_table('candidate_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.Column('gpa', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_education_candidate_id'), 'candidate_education', ['candidate_id'], unique=False)
    op.create_table('candidate_entity_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('from_entity_type', sa.String(length=100), nullable=False),
    sa.Column('from_entity_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.Column('to_entity_type', sa.String(length=100), nullable=False),
    sa.Column('to_entity_id', sa.Integer(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'from_entity_type', 'from_entity_id', 'relation_type', 'to_entity_type', 'to_entity_id', name='uq_candidate_entity_relation')
    )
    op.create_index(op.f('ix_candidate_entity_relations_candidate_id'), 'candidate_entity_relations', ['candidate_id'], unique=False)
    op.create_table('candidate_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_experiences_candidate_id'), 'candidate_experiences', ['candidate_id'], unique=False)
    op.create_table('candidate_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('fact_key', sa.String(length=150), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_facts_candidate_id'), 'candidate_facts', ['candidate_id'], unique=False)
    op.create_table('candidate_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'link_type', 'url', name='uq_candidate_link')
    )
    op.create_table('candidate_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('preference_key', sa.String(length=100), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'category', 'preference_key', name='uq_candidate_preference')
    )
    op.create_index(op.f('ix_candidate_preferences_candidate_id'), 'candidate_preferences', ['candidate_id'], unique=False)
    op.create_table('candidate_profile_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'version_number', name='uq_candidate_profile_version')
    )
    op.create_index(op.f('ix_candidate_profile_versions_candidate_id'), 'candidate_profile_versions', ['candidate_id'], unique=False)
    op.create_table('candidate_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('problem', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('architecture', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_projects_candidate_id'), 'candidate_projects', ['candidate_id'], unique=False)
    op.create_table('candidate_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('publication_type', sa.String(length=100), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_publications_candidate_id'), 'candidate_publications', ['candidate_id'], unique=False)
    op.create_table('candidate_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency_level', sa.String(length=50), nullable=True),
    sa.Column('experience_months', sa.Integer(), nullable=True),
    sa.Column('last_used_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'skill_id', name='uq_candidate_skill')
    )
    op.create_index(op.f('ix_candidate_skills_candidate_id'), 'candidate_skills', ['candidate_id'], unique=False)
    op.create_table('candidate_source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'content_hash', name='uq_candidate_source_document_hash')
    )
    op.create_index(op.f('ix_candidate_source_documents_candidate_id'), 'candidate_source_documents', ['candidate_id'], unique=False)
    op.create_table('candidate_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('story_type', sa.String(length=100), nullable=True),
    sa.Column('situation', sa.Text(), nullable=True),
    sa.Column('task', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_stories_candidate_id'), 'candidate_stories', ['candidate_id'], unique=False)
    op.create_table('candidate_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'name', name='uq_candidate_tag')
    )
    op.create_index(op.f('ix_candidate_tags_candidate_id'), 'candidate_tags', ['candidate_id'], unique=False)
    op.create_table('skill_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_alias')
    )
    op.create_table('candidate_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metric_text', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['experience_id'], ['candidate_experiences.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['candidate_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_achievements_candidate_id'), 'candidate_achievements', ['candidate_id'], unique=False)
    op.create_table('candidate_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_identifier', sa.String(length=255), nullable=True),
    sa.Column('changes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['candidate_source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_audit_log_candidate_id'), 'candidate_audit_log', ['candidate_id'], unique=False)
    op.create_table('candidate_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('education_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('course_code', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['education_id'], ['candidate_education.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_document_parses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('parser_name', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=100), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('structured_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['candidate_source_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_document_id', 'parser_name', 'parser_version', name='uq_candidate_document_parse')
    )
    op.create_table('candidate_entity_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['candidate_tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'entity_type', 'entity_id', name='uq_candidate_entity_tag')
    )
    op.create_table('candidate_experience_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('usage_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['candidate_experiences.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience_id', 'skill_id', name='uq_candidate_experience_skill')
    )
    op.create_table('candidate_project_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['candidate_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'link_type', 'url', name='uq_candidate_project_link')
    )
    op.create_table('candidate_project_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('usage_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['candidate_projects.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'skill_id', name='uq_candidate_project_skill')
    )
    op.create_table('candidate_extracted_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('document_parse_id', sa.Integer(), nullable=True),
    sa.Column('proposed_entity_type', sa.String(length=100), nullable=False),
    sa.Column('proposed_field', sa.String(length=150), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('resolved_entity_type', sa.String(length=100), nullable=True),
    sa.Column('resolved_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['document_parse_id'], ['candidate_document_parses.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['candidate_source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_extracted_facts_candidate_id'), 'candidate_extracted_facts', ['candidate_id'], unique=False)
    op.create_table('candidate_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(length=50), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('extracted_fact_id', sa.Integer(), nullable=True),
    sa.Column('target_entity_type', sa.String(length=100), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('locator_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['extracted_fact_id'], ['candidate_extracted_facts.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['candidate_source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_evidence_candidate_id'), 'candidate_evidence', ['candidate_id'], unique=False)
    op.create_table('candidate_profile_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('conflict_type', sa.String(length=100), nullable=False),
    sa.Column('existing_entity_type', sa.String(length=100), nullable=True),
    sa.Column('existing_entity_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=150), nullable=True),
    sa.Column('incoming_extracted_fact_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolution_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['incoming_extracted_fact_id'], ['candidate_extracted_facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profile_conflicts_candidate_id'), 'candidate_profile_conflicts', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_profile_conflicts_candidate_id'), table_name='candidate_profile_conflicts')
    op.drop_table('candidate_profile_conflicts')
    op.drop_index(op.f('ix_candidate_evidence_candidate_id'), table_name='candidate_evidence')
    op.drop_table('candidate_evidence')
    op.drop_index(op.f('ix_candidate_extracted_facts_candidate_id'), table_name='candidate_extracted_facts')
    op.drop_table('candidate_extracted_facts')
    op.drop_table('candidate_project_skills')
    op.drop_table('candidate_project_links')
    op.drop_table('candidate_experience_skills')
    op.drop_table('candidate_entity_tags')
    op.drop_table('candidate_document_parses')
    op.drop_table('candidate_courses')
    op.drop_index(op.f('ix_candidate_audit_log_candidate_id'), table_name='candidate_audit_log')
    op.drop_table('candidate_audit_log')
    op.drop_index(op.f('ix_candidate_achievements_candidate_id'), table_name='candidate_achievements')
    op.drop_table('candidate_achievements')
    op.drop_table('skill_aliases')
    op.drop_index(op.f('ix_candidate_tags_candidate_id'), table_name='candidate_tags')
    op.drop_table('candidate_tags')
    op.drop_index(op.f('ix_candidate_stories_candidate_id'), table_name='candidate_stories')
    op.drop_table('candidate_stories')
    op.drop_index(op.f('ix_candidate_source_documents_candidate_id'), table_name='candidate_source_documents')
    op.drop_table('candidate_source_documents')
    op.drop_index(op.f('ix_candidate_skills_candidate_id'), table_name='candidate_skills')
    op.drop_table('candidate_skills')
    op.drop_index(op.f('ix_candidate_publications_candidate_id'), table_name='candidate_publications')
    op.drop_table('candidate_publications')
    op.drop_index(op.f('ix_candidate_projects_candidate_id'), table_name='candidate_projects')
    op.drop_table('candidate_projects')
    op.drop_index(op.f('ix_candidate_profile_versions_candidate_id'), table_name='candidate_profile_versions')
    op.drop_table('candidate_profile_versions')
    op.drop_index(op.f('ix_candidate_preferences_candidate_id'), table_name='candidate_preferences')
    op.drop_table('candidate_preferences')
    op.drop_table('candidate_links')
    op.drop_index(op.f('ix_candidate_facts_candidate_id'), table_name='candidate_facts')
    op.drop_table('candidate_facts')
    op.drop_index(op.f('ix_candidate_experiences_candidate_id'), table_name='candidate_experiences')
    op.drop_table('candidate_experiences')
    op.drop_index(op.f('ix_candidate_entity_relations_candidate_id'), table_name='candidate_entity_relations')
    op.drop_table('candidate_entity_relations')
    op.drop_index(op.f('ix_candidate_education_candidate_id'), table_name='candidate_education')
    op.drop_table('candidate_education')
    op.drop_index(op.f('ix_candidate_certifications_candidate_id'), table_name='candidate_certifications')
    op.drop_table('candidate_certifications')
    op.drop_index(op.f('ix_candidate_awards_candidate_id'), table_name='candidate_awards')
    op.drop_table('candidate_awards')
    op.drop_index(op.f('ix_candidate_application_facts_candidate_id'), table_name='candidate_application_facts')
    op.drop_table('candidate_application_facts')
    op.drop_index(op.f('ix_candidate_activities_candidate_id'), table_name='candidate_activities')
    op.drop_table('candidate_activities')
    op.drop_table('skills')
    # ### end Alembic commands ###
