"""add jobs deduplication constraint

Revision ID: b752f47f70b6
Revises: 773ab98e60da
Create Date: 2026-09-17 23:53:25.613600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b752f47f70b6'
down_revision: Union[str, Sequence[str], None] = '773ab98e60da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_jobs_source_job_id', 'jobs', ['source', 'source_job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_jobs_source_job_id', 'jobs', type_='unique')
    # ### end Alembic commands ###
