"""add candidate profiles table

Revision ID: d6ee58f68633
Revises: d305ce1de30d
Create Date: 2026-09-18 18:29:41.654517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ee58f68633'
down_revision: Union[str, Sequence[str], None] = 'd305ce1de30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('professional_headline', sa.String(length=255), nullable=True),
    sa.Column('professional_summary', sa.Text(), nullable=True),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('current_country', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###
